-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."packs" add column "list_publicly" boolean
--  not null default 'false';
