version: '3.7'
services:
    postgres:
        image: postgres:15-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - /tmp/postgres-data:/var/lib/postgresql/data
