-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."nfts" add column "wallet_age_check" boolean
--  not null default 'False';
