# An attempt at solving a puzzle
query Guess($puzzle_id: uuid!, $solution: String!) {
  fail: puzzles_by_pk(puzzle_id: $puzzle_id) {
    fail_route
  }
  success: puzzles(
    where: { puzzle_id: { _eq: $puzzle_id }, solution: { _ilike: $solution } }
  ) {
    # success_puzzle
    success_route
  }
}

# We need char count for certain puzzles
query SolutionCharCount($puzzle_id: uuid!) {
  solution: puzzles_by_pk(puzzle_id: $puzzle_id) {
    solution_char_count
  }
}
